spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: employee-service
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:employee
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: admin
    password: admin

  security:
    user:
      name: admin
      password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 8761
server:
  port: 8083

logging:
  level:
    #web: debug
    #root: debug
    sql: trace